package com.ferreteriapfeifer.ferreteria_api.controller;

public class LoginAdminController {
    //TODO: IMPLEMENTAR JWT PARA EL LOGIN Y VALIDACIÓN DE ENDPOINTS (EJ MODIFICARSTOCK SOLO DISPONIBLE PARA ADMIN, COMPRAS SOLO DISPONIBLE PARA USUARIOS CON JWT, ETC) USANDO EL HEADER AUTHORIZATION
    //TODO: NO DEJAR EN LOS CLAIMS DATA SENSIBLE, EJ CONTRASEÑA
    //TODO: ENCRIPTAR CONTRASEÑAS DE CLIENTE Y ADMIN
    //TODO:
}
